DROP TABLE loan_acq_data;
CREATE TABLE loan_acq_data AS
SELECT LOAN_ID, 
	ORIG_CHN, 
	to_number(ORIG_RT) AS ORIG_RT, 
	to_number(ORIG_AMT) AS ORIG_AMT, 
	to_number(ORIG_TRM) AS ORIG_TRM, 
	to_date(FRST_DTE) AS FRST_DTE,
	to_number(OLTV) AS OLTV, 
	to_number(OCLTV) AS OCLTV, 
	to_number(NUM_BO) AS NUM_BO, 
	to_number(DTI) AS DTI, 
	to_number(CSCORE_B) AS CSCORE_B, 
	FTHB_FLG, 
	PURPOSE, 
	PROP_TYP, 
	to_number(NUM_UNIT) AS NUM_UNIT,
	OCC_STAT, 
	STATE, 
	to_number(ZIP_3) AS ZIP_3, 
	to_number(MI_PCT) AS MI_PCT, 
	PRODUCT_TYPE, 
	"FANNIE_MAE" as AGENCY
from fannie_mae_acq
UNION ALL
SELECT id_loan as LOAN_ID, 
	channel as ORIG_CHN, 
	to_number(int_rt) as ORIG_RT, 
	to_number(orig_upb) as ORIG_AMT, 
	to_number(orig_loan_term) as ORIG_TRM, 
	to_date(dt_first_pi) as FRST_DTE,
	to_number(ltv) as OLTV, 
	to_number(cltv) as OCLTV, 
	to_number(cnt_borr) as NUM_BO, 
	to_number(dti) as DTI, 
	to_number(fico) as CSCORE_B, 
	CASE WHEN flag_fthb=" " THEN "U" ELSE flag_fthb END as FTHB_FLG, 
	CASE WHEN loan_purpose="N" THEN "R" ELSE loan_purpose END as PURPOSE, 
	prop_type as PROP_TYP, 
	to_number(cnt_units) as NUM_UNIT,
	CASE WHEN occpy_sts="O" THEN "P" ELSE occpy_sts END as OCC_STAT, 
	st as STATE, 
	to_number(zipcode) as ZIP_3, 
	CASE WHEN mi_pct = "000" THEN "" ELSE to_number(mi_pct) END as MI_PCT, 
	prod_type as PRODUCT_TYPE,
	"FREDDIE_MAC" as AGENCY
from freddie_mac_acq
